# Generated by Django 2.2.13 on 2020-06-18 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='aritcle',
            new_name='article',
        ),
    ]
